### ISSUE TITLE
can't see deployments to dev or prod

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/LMIS-Dashboard#105]
merged changes are not visible in the dev environment and releases are not being pushed to production.

if these are unrelated, i can make this into 2 tickets

**Comment by tlvince** [comment]
@janetbutts could you check whether http://lomis.ehealth.org.ng/ contains what you're expecting now?

**Comment by tlvince** [comment]
See https://github.com/eHealthAfrica/ehealth-deployment/issues/579

**Comment by janetbutts** [comment]
@tlvince , no, the update hasn't been made. the code for the facility page should have been updated to show facility detail. this is not in place.
