### ISSUE TITLE
create login account for the sio and es

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/LMIS-Dashboard#79]
Give accounts full access

**Comment by janetbutts** [comment]
hey @norbert, can you please create the following accounts with the same access as the slo user for move's dashboard?
user/name	password
es.phcmb@kano.org.ng
dedc.phcmb@kano.org.ng
slo.phcmb@kano.org.ng

I will send the passwords in a separate email.

**Comment by norbert** [comment]
Done!
