### ISSUE TITLE
make facility page duplicate the spreadsheet facility reporting rules

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/LMIS-Dashboard#96]
https://docs.google.com/spreadsheets/d/1Ew4QoizC9jU8I-f9FaCTnU2sHZGdar8zMkOKFQ6GLzQ/edit#gid=842299617

**Comment by jofomah** [comment]
@janetbutts i think Musa is the one working on adding reporting and non-reporting and faulty phone pie chart etc to facility page.
